version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  streamlit:
    build:
      context: .  # Path to Streamlit Dockerfile
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8501:8501"  # Expose Streamlit on port 8501
    depends_on:
      - fastapi  # Ensure FastAPI starts before Streamlit
    networks:
      - app-network
    environment:
      - FASTAPI_URL=http://fastapi:80 # Use service name as hostname

networks:
  app-network:
    driver: bridge
